# in _config.yml
title: "MENACE Revisited"
author                      : Romilly Cocking
copyright                   : "2020"
logo: images/Tic_Tac_Toe.png
execute:
  execute_notebooks: "off"
repository:
  url                       : https://github.com/romilly/o-x-o
  html:
    use_repository_button: true
    use_issues_button: true
    use_edit_page_button: true
html:
  google_analytics_id: UA-26986725-2